### ISSUE TITLE
[Bug, uureport] After adding a TOC, the paragraph layout is reset

### ISSUE THREAD

**Issue by lucvanderzandt** [UtrechtUniversity/uucls#14]
## Expected Behavior
The paragraph layout should only be changed where this is expected (e.g., table of contents, reference list).

## Current Behavior
When adding a table of contents to the document, the paragraph layout of the remaining content uses the same paragraph layout as the TOC.

## Possible Solution
Taking a quick glance at the code, the issue seems to originate from uureport.cls, line 456: ` \parskip\z@`. The `\parskip` variable is not reset to the previous value. A possible solution could be to temporarily store the previous value and reset the `\parskip` variable after constructing the TOC.

## Steps to Reproduce
1. Open or create a document using the uureport.cls class.
2. Add a table of contents using `\tableofcontents`.
3. Notice how the paragraph layout is changed after the TOC.

## Environment
Tex Live 2022 using Overleaf.

**Comment by jkorb** [comment]
Hi @lucvanderzandt ! Thanks so much for reporting this. I'm sorry I'm only getting around to this now, but this was square in the center of my holiday period. I'll double check to confirm and check the PR (#15 ). Again thanks so much and I'll be back soon :+1:
